# Generated by Django 5.2.8 on 2025-12-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
            ],
        ),
    ]
